#ifndef _WAYWARD_METRICS_REPORTING_CONSTANTS_H_
#define _WAYWARD_METRICS_REPORTING_CONSTANTS_H_

#define METRICS_METHOD_START_SESSION                101
#define METRICS_METHOD_SET_PROTOCOL_VERSION         102
#define METRICS_METHOD_RECORD_DATA                  103
#define METRICS_METHOD_OBSERVE_SESSION              104
#define METRICS_METHOD_STOP_OBSERVING_SESSION       105
#define METRICS_METHOD_RETRIEVE_SESSION             106
#define METRICS_METHOD_DELETE_SESSION               107
#define METRICS_METHOD_LIST_SESSIONS                108

#endif

